### ISSUE TITLE
A站近几天又更新了，现在番剧解析失效，登会员也没用

### ISSUE THREAD

**Issue by YFTX2015** [nICEnnnnnnnLee/AcFunDown#1]

**Comment by nICEnnnnnnnLee** [comment]
我想应该是最新的番剧下载有问题，这种类型的链接解析的时候没有考虑进去，新版本已加入

+ V0.2 版本
`https://www.acfun.cn/member/#area=favourite` (收藏夹，登录后支持)√
`https://www.acfun.cn/u/14539629.aspx` （UP上传视频）√
`https://www.acfun.cn/v/ac10880620` √
`https://www.acfun.cn/bangumi/aa5024869` √
`https://www.acfun.cn/bangumi/ab5024869_34168_334763` √
`https://www.acfun.cn/bangumi/ab5024869` ×

+ V0.3 版本
`https://www.acfun.cn/member/#area=favourite` (收藏夹，登录后支持)√
`https://www.acfun.cn/u/14539629.aspx` （UP上传视频）√
`https://www.acfun.cn/v/ac10880620` √
`https://www.acfun.cn/bangumi/aa5024869` √
`https://www.acfun.cn/bangumi/ab5024869_34168_334763` √
`https://www.acfun.cn/bangumi/ab5024869` √
