### ISSUE TITLE
如何在config中设置下载后视频的名字

### ISSUE THREAD

**Issue by zywzyw1234567** [nICEnnnnnnnLee/AcFunDown#10]
如题，就是像bilibilidown里面一样，可以修改app来设置视频名称，并分up主名字分文件夹保存

**Comment by nICEnnnnnnnLee** [comment]
你可以复制[app.config](https://github.com/nICEnnnnnnnLee/AcFunDown/blob/master/src/resources/app.config)到config目录下，然后做相应改动。

**Comment by nICEnnnnnnnLee** [comment]
但是没法分文件夹保存

**Comment by zywzyw1234567** [comment]
> 你可以复制[app.config](https://github.com/nICEnnnnnnnLee/AcFunDown/blob/master/src/resources/app.config)到config目录下，然后做相应改动。

试过，复制过来把文本中bilibili全都替换成acfun，但加“upname/”没法分文件夹保存

**Comment by zywzyw1234567** [comment]
> 但是没法分文件夹保存

哦哦。好吧
