### ISSUE TITLE
满月之战11集下载错误

### ISSUE THREAD

**Issue by YFTX2015** [nICEnnnnnnnLee/AcFunDown#3]
![屏幕截图(29)](https://user-images.githubusercontent.com/12757305/65064835-cfc9e800-d9b3-11e9-8756-96b5e5ad0666.png)
第10集下完后，再下十一集就变成这样了。
页面地址：https://www.acfun.cn/bangumi/ab5024870
估计是解析地址后面的番号出问题。

**Comment by nICEnnnnnnnLee** [comment]
+ 确实存在问题:flushed:，下个版本修复。
+ 临时解决方案：
    + **方案一**: 
          + 在程序里面下载将`ab5024870`改成`aa5024870`
          + 从里面选择第11集下载
    + **方案二**:
          + 浏览器打开<https://www.acfun.cn/bangumi/aa5024870>
          + 进入第十一话，然后得到<https://www.acfun.cn/bangumi/ab5024870_34169_336056>
          + 在程序里面下载`ab5024870_34169_336056`

**Comment by YFTX2015** [comment]
对头，必须要ab5024870后面那两组数字才能下载到想要的集数。还有一种办法就是在acfun页面先切换到第十集，然后再切换转来，这样十一集地址后面也有那两组数字，再输进程序就能正常下载了。

**Comment by nICEnnnnnnnLee** [comment]
这是A站API分页造成的，估计默认每页是10个，偷懒没写 :flushed:
<https://www.acfun.cn/album/abm/bangumis/video?albumId=5024870>  ×
<https://www.acfun.cn/album/abm/bangumis/video?albumId=5024870&num=1&size=1000> √

还有一个_t时间参数省略了

**Comment by YFTX2015** [comment]
喔，这个我就不懂了
