### ISSUE TITLE
想要搜索番剧时一直正在加载中

### ISSUE THREAD

**Issue by yssa04** [nICEnnnnnnnLee/AcFunDown#4]
![MHB@9_3EV1}M@DJ4N68_) W](https://user-images.githubusercontent.com/49361531/65738618-15ee1c80-e115-11e9-9709-fd441436c9f9.png)
是我自己的问题吗 其它视频倒是可以 番剧却不行

**Comment by nICEnnnnnnnLee** [comment]
卧槽，a站又更新了:flushed:

**Comment by nICEnnnnnnnLee** [comment]
老铁，先把链接里面的`aa`改成`ab`应急，最近我再发个版本
`https://www.acfun.cn/bangumi/aa5024886` -->`https://www.acfun.cn/bangumi/ab5024886`
`aa5024886_36188_330164` --> `ab5024886_36188_330164`

**Comment by yssa04** [comment]
好的 谢谢

**Comment by yssa04** [comment]
好的 谢谢

> 老鐵，先把鏈接裡面的`aa`改成`ab`應急，最近我再發個版本
> `https://www.acfun.cn/bangumi/aa5024886`-> `https://www.acfun.cn/bangumi/ab5024886`
> `aa5024886_36188_330164`->`ab5024886_36188_330164`
