### ISSUE TITLE
索斯机兽zero无法下载

### ISSUE THREAD

**Issue by YFTX2015** [nICEnnnnnnnLee/AcFunDown#5]
这是付费番剧，付费后第二集能够下载，但是第三集就不能下载了，倒是能够解析出剧名，集数，也有下载按钮，但是点击之后下载页面却没有建立任何下载任务。

**Comment by nICEnnnnnnnLee** [comment]
...
刚刚试了一下，番剧链接的获取接口已经失效了，应该是所有番剧都下不了了。。。
我再看看好了

**Comment by nICEnnnnnnnLee** [comment]
+ `v0.5`的问题是，A站的接口失效，所有的番剧都没法下载
+ `v0.6`改从网页里面爬，解决了这一问题。
    + 但是，需要付费的那种**可能**仍然不行 - 这取决于A站是根据cookies返回不同的网页内容，还是在网页加载完后，再发一个异步请求。

**Comment by nICEnnnnnnnLee** [comment]
已经更新了一个版本，试试看吧亲:flushed:

**Comment by YFTX2015** [comment]
嗯，回去试。不过它这个比亚马逊视频，网飞剧还要变态，那些至少还能下下来，只不过是加密过的，要破解才能放，A站付费的连下都下不下来。

**Comment by YFTX2015** [comment]
硕鼠现在对于a站没加密视频包括番剧还能解析出m3u8链接，集数识别也没问题，不过对于付费视频是无论如何也解析不出链接的。

**Comment by YFTX2015** [comment]
试过了，付费视频可以下，但是是低清晰度，下不了1080P。然后，重新下载的话又会跟以前版本一样显示已经下载过，从而无法下载第二次。

**Comment by YFTX2015** [comment]
又试过下载其它非付费番剧，同样无法获取1080P，只能得到低清晰度的版本了。

**Comment by nICEnnnnnnnLee** [comment]
想要1080P的，你点击标清下载好了:flushed:
不是啥大问题，最近不改了

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> 重新下载的话又会跟以前版本一样显示已经下载过，从而无法下载第二次。

+ 如果你想关闭这个功能，在`config`文件夹下创建一个[`app.config`](https://github.com/nICEnnnnnnnLee/AcFunDown/blob/master/src/resources/app.config),然后把
`acfun.repo = on` 修改为 `acfun.repo = off`  然后     
    + 重新打开程序
    + 或者 `菜单 -> 操作 -> 重新加载配置`

+ 如果你想保留这个功能，只想再下一遍特定视频，将`config/repo.config`里面的相应记录删除，然后     
    + 重新打开程序
    + 或者 `菜单 -> 操作 -> 重新加载仓库`

**Comment by YFTX2015** [comment]
OK，不过清晰度那个变化最好还是在更新日志里面标注说明，不然会引起别人混淆

**Comment by YFTX2015** [comment]
v0,7启动时已自动登录一位用户，但是就不能下载付费视频了，付费视频必须要给钱才能下载，而且还不能切换用户。所以希望作者增加切换用户功能，另外，也希望增添直接手动输入账号密码登录的方式，谢谢！

**Comment by nICEnnnnnnnLee** [comment]
+ 切换用户，将config文件夹下的cookies.config删除，再重启程序即可
  
  
    + 用户名密码登录工作量太大，同时可能需要引入很重的依赖，不在计划中

**Comment by YFTX2015** [comment]
主要是看了JJDOWN都是用账号密码登陆，还以为很简单，没想过会有那么复杂。既然如此，在这方面我就不再提要求了。话说，现在解析出来1080P文件体积是越来越小了。
