### ISSUE TITLE
[V0.6]番剧清晰度提示有误

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/AcFunDown#6]
又试过下载其它非付费番剧，同样无法获取1080P，只能得到低清晰度的版本了。

_Originally posted by @YFTX2015 in https://github.com/nICEnnnnnnnLee/AcFunDown/issues/5#issuecomment-544281921_

`标清 - 高清 - 超清 - 1080P` 的实际清晰度应该为
`1080P - 超清 - 高清 - 标清`

**Comment by YFTX2015** [comment]
经过我再次实际测试下载A站不同番剧，发现说得清晰度并不一定遵循上述规则，一部分是选择啥清晰度得到的就是对应的清晰度，而一部分则是按照选择的清晰度得到的并非是对应的清晰度或者是作者上述的清晰度。比如，有一部番剧，我选择的是高清，实则得到1080P，还有一部番剧我选择的是超清，得到的是1080P，但还未遇到过标清得到1080P的情形。另外，得到的1080P文件大小全是三四百多兆，这与原来A站一部24分钟左右的1080P番剧平均文件大小五百多兆的情况有出入，不晓得是A站本身就减少了1080P的文件容量还是此版本软件解析出现问题。

**Comment by nICEnnnnnnnLee** [comment]
+ A站番剧的M3U8会提供四个播放源，分别对应四种清晰度。比如：
```
#EXTM3U
#EXT-X-VERSION:4
#EXTINF:0.000000,
C-wgInCTMIAv0OgFV8_qV-2kwdTEkozSTgaYmpg645gZsjn5MCWk8whWEtlPvqlL.m3u8?safety_id=AALHKqLSSuUWRulBF5foODKW&pkey=AAPGTChfJreehdhXl5OK4nHrpK5QqRmu24G5IJ0om49tJaIcd8_pBXamV_3qoog9BShsKmw1kBKXjpTWOZVOPp3KJVDHoDoxZeZQTdA_hK1gugdfXcjred8Aj7ewcl8-HqWzv6rsgVHHdnSnAwR_q95oekX4MxDF0rNo_MOyttaiSY0MK4YF5g1-nUMTFN6wWfLaQ4JH8S2ZAmREzrkjIuxNcwNHty0gBwRwQWcDZIpUlT7DNi02YyGPZA66KQ5qXESkF6v8FwTnRb3JtgJiw5LGUfWZU2NOCx66SwnAGcuKwQ
#EXTINF:0.000000,
C-wgInCTMIAv0OgFV8_qVwVYNnC8X3C48EHSoUCt2dsdgJ8a2taPOILzz8OwwUdh.m3u8?safety_id=AALHKqLSSuUWRulBF5foODKW&pkey=AAMVfFH-326UIDwsrSVp5HgtkD0y3WmcCK24HJVaeMCFKAOlAvrycB_Mr7dT2q3Srx-LB1jlf66sRfz5uClA9bI2wrukClJubVN13Y0_29aRcDWPgAYHcwpT4j3CVSWehU7nDxeZphSeE103rMaKLdZOTgJk1vx2dWXW9BKIFLLZcs2_9V60nh4BWl7-hXhe-H7lZM5LxbioRal0B3caGg1xUB4nA8xELfHUHZPPCTcQLvwIfaM9pIGeyl9TAjrurMn8xNGCDMJ3VIGRpfBr9JgqyVFLh1rwIbR9fohqzhLyQg
#EXTINF:0.000000,
C-wgInCTMIAv0OgFV8_qV_9Ij5xyGQS_uBfTPO-bxxnbNvpu7wlDhzq6chjbMlrS.m3u8?safety_id=AALHKqLSSuUWRulBF5foODKW&pkey=AAOj18ZwHIWin41R6FQDUoyFCjuwQNdaF40bGJksmcwdihtmEbkGwEMHzzS7_92wcH-v5dLLz56jdtyRIS0DlFLo264uksE42Y1ooCK3mlDu97-0YPSXeNS3wNcXBLUkKgPjpBAgiZu1qXExVyaHbyQiiFxrD1i5hgiIl5cwcA-W4UygHmbmUkTtYWHoJNTKSHhyJNIacr3icckszTTUBvZTaVt-ThAGzKKOSTbaU_lAK-FRUThXhE4yw8yKCDjQX4Apyop5ucPTunGS9f39DIkBfBuPATA_IxILmb8ORHY3cQ
#EXTINF:0.000000,
v-MXUN2BdwtDQqdloSHbss1BlNl9sevRRE9nUtL8MYs_0giZWOWZFbf9QoyKey8T.m3u8?safety_id=AALHKqLSSuUWRulBF5foODKW&pkey=AAPWlvoaEv74HtDexPpPCA7GFt2pSmMmzQWY6WD1FOt9FkauDUZhxL03XXT_nFLpVTK1XJOkyVrojp7dO1cEBl265oLJ4bYi5PeaLkwKDPGtoo9tZdwwkPoNLipBy-6GgUnDsRAYHAHUQMIldWvGdDkry9GqmF1iLF2AGj5ge1WNwCEGAWHcm0shbgMjT05NQj14aM2OKIEjI8pncTWxwyLQ5uqma1EB1GXudDwwq0VzRo-jLvxowxq3sOzSTkoZ_nteUU7m17ECeXWKdTOmeiJDAkGVJ1Y8vma8DYlcEBrUGQ
```
+ 默认是认为从上到下清晰度逐渐变好。  
一开始根据反馈，我以为这个清晰度顺序搞反了。  
再次反馈后，我本地测试了一下，发觉似乎没有啥严格对应关系。。。
    + aa5023295 - p25 新世纪福音战士 第26话 √
![qn-2](https://user-images.githubusercontent.com/19970934/67214776-e64fdd00-f452-11e9-807e-a80438aabc7d.png)
    + aa6000307_36188_338412 索斯机兽ZERO-爆裂的武器库 巴祖卡鳄龟  √
![qn-1](https://user-images.githubusercontent.com/19970934/67214797-ee0f8180-f452-11e9-91ba-27691c512351.png)
    + aa6000351 p1 索斯机兽ZERO（中配）-pn1-爆裂的武器库 巴祖卡鳄龟 ×
![qn-3](https://user-images.githubusercontent.com/19970934/67216870-7d6a6400-f456-11e9-8725-06f71771e8e7.png)

**Comment by nICEnnnnnnnLee** [comment]
我再想想办法吧:flushed:
