### ISSUE TITLE
输入up主页面，无法批量下载

### ISSUE THREAD

**Issue by zywzyw1234567** [nICEnnnnnnnLee/AcFunDown#9]
比如像
https://www.acfun.cn/u/6015530
就无法下载这个up所有视频，不像bilibilidown那样
如何批量下载呢

**Comment by nICEnnnnnnnLee** [comment]
好久没关注，A站又更新了

**Comment by zywzyw1234567** [comment]
> 好久没关注，A站又更新了

跪求大佬有空动动手指，我AB两站双修的5555555

**Comment by zywzyw1234567** [comment]
谢谢大佬，已经可以下载了
